# Site settings
title: czb1n's Den
description: '梦要自己扛，泪要自己尝。'
keyword: 'Server iOS Java Kotlin Swift Objective-C 技术 程序员'
url: 'http://www.zbin.tech/'
baseurl: ''

author:
  name: 'czb1n'
  email: 317646534@qq.com
#  facebook_username: czb1n
  github_username:  czb1n

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

baidu-analysis: a14b0dbc71bff63c2370f65118b12426

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
